name: 'orderly'
description: 'Action to run an orderly workflow on Packit.'
inputs:
  packit-url:
    type: 'string'
    description: 'URL of a packit instance'
    required: true

  reports:
    type: 'string'
    description: 'List of reports to run'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        data=$(mktemp)
        echo '${{ inputs.reports }}' > $data
        Rscript --verbose '${{ github.action_path }}/run.R' '${{ inputs.packit-url }}' "$data"
